### PR TITLE
Refactor if/elif to remove repeated code

### PR DESCRIPTION
**Pull request by wakfi**
Enhances readability and maintainability as changes to the embed only need to be made once

### CODE REVIEW

**Comment by SSwiftGamer440** [comment]
Here's a better idea, make the output a function, and run the function whenever needed

**Comment by wakfi** [comment]
For the embed generation? Would we use it elsewhere?

**Comment by SSwiftGamer440** [comment]
Yes, for the embed generation Wakfi.
if we put it in a func, we can just call upon the func and save several code lines

**Comment by wakfi** [comment]
I think that would add lines of code if its not going to be used in any other command

**Comment by SSwiftGamer440** [comment]
It would still save code though, change it and i will merge it

**Comment by wakfi** [comment]
Change made. It's longer now, but your call

**Comment by SSwiftGamer440** [comment]
MERGE APPROVE:

**Comment by SSwiftGamer440** [comment]
MERGED, CLOSE:

**Pull request merged**
