### PR TITLE
Ping updated to include client latency

### PR DESCRIPTION
**Pull request by NapkinsXYZ**

### CODE REVIEW

**Comment by wakfi** [comment]
Is this Pull request still needed?

**Comment by NapkinsXYZ** [comment]
no

**Comment by SSwiftGamer440** [comment]
REOPEN: This PR can still be edited

**Comment by wakfi** [comment]
It is a hassle to do

**Comment by SSwiftGamer440** [comment]
no it is not wakfi
I added it easily
bot.latency*1000

**Comment by wakfi** [comment]
I mean using the unused pull request

**Comment by SSwiftGamer440** [comment]
oh
anyway, stop posting here rofl

**Comment by wakfi** [comment]
No u :dapJuicyPeek:

**Pull request closed without merging**
